## 数据源1配置
mysql:
  master:
    type: com.alibaba.druid.pool.DruidDataSource
    mapperLocations: classpath:mapper/master/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml
    datasource:
      url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    ## 数据源2配置
  cluster:
    type: com.alibaba.druid.pool.DruidDataSource
    mapperLocations: classpath:mapper/cluster/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml
    datasource:
      url: jdbc:mysql://localhost:3306/springbootdb_read1?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

