server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

#mybatis配置
mybatis:
  type-aliases-package: com.wujun.boot.domain
  mapper-locations: classpath:mapper/*.xml
#  config-location: mybatis/mybatis-config.xml




