server:
  port: 8081
#logback\u65E5\u5FD7\u914D\u7F6E
logging:
  path: /Users/wujun/codelib/boot_leaning/springboot_dubbo_consumer/log
  config: classpath:logback/logback.xml
  level: info

wujun:
  dubbo:
    application:
      name: dubbo-wujun-boot-starter-consumer-test
      owner: wujun
    registry:
      address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2181,127.0.0.1:2181
      file: dubboCache/wujun-boot-web
    monitor:
      address: dubbo://127.0.0.1:7070
    protocol:
      port: 20886
#    provider:
#      version: 1.0.1
#      group: wujun_default_dev
    consumer:
      version: 1.0.1
      group: wujun_default_dev
      enable: true
      references:
        - interfaceClass: com.wujun.boot.service.TestService
          beanId: testDubboService
#          async: true
    provider:
      group: wujun_default_dev
      version: 1.0.1
      enable: true
      services:
        - interfaceClass: com.wujun.boot.service.TestService2
          ref: testDubboService2
